# This is a dev only ammenity
services:
  db:
    image: mysql
    restart: always
    container_name: real-world-adianti
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db
